# Generated by Django 5.2.17 on 2026-09-25 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_id', models.CharField(max_length=64)),
                ('log_date', models.DateField()),
                ('ingested_at', models.DateTimeField(auto_now=True)),
                ('rejected_rows', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-log_date'],
                'constraints': [models.UniqueConstraint(fields=('clinic_id', 'log_date'), name='unique_clinic_day')],
            },
        ),
        migrations.CreateModel(
            name='BillingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('doctor_id', models.CharField(blank=True, default='', max_length=64)),
                ('line_items', models.JSONField(default=list)),
                ('payment_mode', models.CharField(choices=[('cash', 'cash'), ('card', 'card'), ('upi', 'upi')], max_length=8)),
                ('amount_paid_paise', models.BigIntegerField()),
                ('discount_paise', models.BigIntegerField(default=0)),
                ('is_refund', models.BooleanField(default=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='billing.billingday')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
